### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by carlosvigil** [kbladin/KalleWheel#1]
Mainly asking what the right arrow/chevron button does. There are no text descriptions in the extension. Might be a bug; i'm running CC18 on macOS High Sierra.

Another thing, rather a suggestion is that the palette feature be removed, and sampling from PS colors be automatic. Sampling from KalleWheel should still be manual. And for saving colors the native palette panel is sufficient.

I could write it in if I got some guidance, as I've never made a CC extension, though it seems to be web tech which I know.

Thanks for the ext! Only magic picker competes though it's $20.

**Comment by kbladin** [comment]
Arrow buttons were removed in previous version. They were used to export and import colors which is now done automatically.
