### ISSUE TITLE
Error message pops up when opening photoshop

### ISSUE THREAD

**Issue by Zdele1** [kbladin/KalleWheel#10]
happens only when the wheel panel is open, if its collapesd to icon there is no message. 

![image (1)](https://user-images.githubusercontent.com/64246807/80181077-72aaaa80-8604-11ea-9646-5b86e7371659.png)

**Comment by kbladin** [comment]
This most likely means that the PS version you have does not support the event features required for some functionalities in the extension. The error message has been made clearer in 2f05ceab60ba55fa67771c3c15b48e442009fd38
