### ISSUE TITLE
Sliders aren't dragable 

### ISSUE THREAD

**Issue by Zdele1** [kbladin/KalleWheel#22]
I am unable to click and drag sliders, I can only click on the location on the sliders to make the change.
When i try to click and drag, sliders move a bit but stop quickly. After i remove the pen from the tablet the slider is still sometimes stuck to it and starts skipping around. I need to click somwhere else to unstuck them.

This issue appeared only after i started using windows ink, since it fixed the no pressure on first stroke bug. and i have tested it without windwos ink and i can drag sliders normally. Also i tested it with windows ink on other slider plugins, and there are no issues there - coolorus, cameleon pallette, default photoshop lab sliders can all be clicked and dragged normally.

**Comment by Zdele1** [comment]
This is probably related to the this issue, but also sometimes when using the sliders after adjusting lightness first stroke doesen't register the adjustment, but uses the old color instead

![image](https://user-images.githubusercontent.com/64246807/81178156-105c8d00-8fa8-11ea-9137-d6429ec98b08.png)

**Comment by kbladin** [comment]
Problem exists on mac as well. For me it appeared after updating from Photoshop 2018 to 2020. It's somehow related to Adobes integration of Chromium Embedded Framework. The slider is simply a html input range element. Could potentially be fixed with a custom slider implementation.

**Comment by Zdele1** [comment]
Just  to update, I reverted back to PS 20.0.3 using wintab as stylus service, and sliders work normally, only when using buggy windows ink they arent dragable

**Comment by kbladin** [comment]
Problem solved on Adobe's side with PS 2021
