### ISSUE TITLE
Old version on Adobe Marketplace?

### ISSUE THREAD

**Issue by luizpaulo165** [kbladin/KalleWheel#24]
Hi.
I installed the extension using the Adobe's Marketplace but when I opened my PS the tool haven't the same options than image on description:

My PS:
![Screenshot 2020-07-30 at 10 07 34](https://user-images.githubusercontent.com/573227/88926811-e1735180-d24c-11ea-8d3d-2daf3219ea64.png)

Img on description:
![Screenshot 2020-07-30 at 10 07 43](https://user-images.githubusercontent.com/573227/88926838-ec2de680-d24c-11ea-893d-5fa3a74cdbec.png)

I'm using PS 2020 on Mac. Is it a problem or on mac does not have thats option?

**Comment by kbladin** [comment]
Hi, the version on the market place has not yet been updated. The current version available on github is a kind of beta version.
